var WebSocket = require('ws');
var clientTemplate = require('raw-loader!./client.tpl.js');
var wrapTemplate = require('raw-loader!./wrap.tpl.js');
var _ = require('lodash');

module.exports = function({
    start = true,
    port = 3100,
} = {}) {
    let wss;

    function startServer() {
        wss = new WebSocket.Server({ port });
    }

    function reload({ file, path, angular = 'angular' }) {
        const message = wrap(file, path, angular);

        wss.clients.forEach(client => {
            if (client.readyState = WebSocket.OPEN) {
                client.send(message);
            }
        });
    }

    const clientOptions = {
        port,
        ns: 'ng-hot-reload-standalone',
    };

    function wrap(file, path, angular) {
        const options = _.assign({
            path,
        }, clientOptions);

        return `
        ;// Generated by ng-hot-reload-standalone...
        (function(__ngHotReloadOptions) {
            ${wrapTemplate}  
        // ...Generated content ends.

            ${file}
        
        // Generated by ng-hot-reload-standalone...
            ;
        })((function(){
            var options = ${ JSON.stringify(options) };
            options.angular = ${ angular };
            return options;
        )());
        // Generated content ends.
        `;
    }

    const client =
        `;(function(options) {
            options.root = typeof window !== 'undefined' ? window : this;

            if (options.root) {
                if (options.root[options.ns]) return;
                else options.root[options.ns] = {};
            }

            ${clientTemplate}

        })(${ JSON.stringify(clientOptions) });
        `;

    if (start) {
        startServer();
    }

    return {
        start: startServer,
        reload,
        client,
    };
};
